# Generated by Django 5.0.2 on 2024-06-13 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Socios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_socio', models.IntegerField(default=0, max_length=1)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=50)),
                ('dni', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.CharField(max_length=16)),
                ('teléfono', models.CharField(max_length=20)),
                ('ciudad', models.CharField(max_length=30)),
                ('provincia', models.CharField(max_length=35)),
                ('socio', models.BooleanField(default=False)),
                ('talla_camiseta', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], default='S', max_length=4)),
            ],
        ),
    ]
