# Generated by Django 5.0.2 on 2024-06-13 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Socios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socios',
            name='numero_socio',
            field=models.IntegerField(default=0),
        ),
    ]
