# Generated by Django 5.0.2 on 2024-06-14 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Socios', '0004_rename_teléfono_socios_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socios',
            name='codigo_postal',
            field=models.CharField(default=14550, max_length=20),
        ),
    ]
