# Generated by Django 5.0.2 on 2024-06-14 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Socios', '0005_alter_socios_codigo_postal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscripciones',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('destino', models.CharField(blank=True, max_length=30)),
                ('fecha', models.CharField(blank=True, max_length=16)),
                ('distancia', models.IntegerField(blank=True)),
                ('dificultad', models.CharField(choices=[('BAJA', 'BAJA'), ('MEDIA-BAJA', 'MEDIA-BAJA'), ('MEDIA-ALTA', 'MEDIA-ALTA'), ('ALTA', 'ALTA')], default='BAJA', max_length=20)),
                ('precio_socio', models.PositiveIntegerField()),
                ('precio_no_socio', models.PositiveIntegerField()),
            ],
        ),
    ]
