# Generated by Django 5.0.2 on 2024-06-14 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Socios', '0006_inscripciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripciones',
            name='finalizada',
            field=models.BooleanField(default=False),
        ),
    ]
