# Generated by Django 5.0.2 on 2024-06-14 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Socios', '0007_inscripciones_finalizada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripciones',
            name='distancia',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
