# Generated by Django 5.0.2 on 2024-06-18 11:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Socios', '0008_alter_inscripciones_distancia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscripcion_Socio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('precio', models.PositiveIntegerField(default=0)),
                ('numero_bus', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)])),
                ('asiento_bus', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(110)])),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Socios.inscripciones')),
                ('socios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Socios.socios')),
            ],
        ),
    ]
