# Generated by Django 5.0.2 on 2024-06-18 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Socios', '0009_inscripcion_socio'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion_socio',
            name='ocupado',
            field=models.BooleanField(default=False),
        ),
    ]
