# Generated by Django 5.0.2 on 2024-06-18 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Socios', '0010_inscripcion_socio_ocupado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscripcion_socio',
            name='ocupado',
        ),
    ]
