# Generated by Django 5.0.2 on 2024-06-19 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Socios', '0011_remove_inscripcion_socio_ocupado'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripciones',
            name='recaudacion_no_socios',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inscripciones',
            name='recaudacion_socios',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
