# Generated by Django 5.0.2 on 2024-06-26 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Socios', '0012_inscripciones_recaudacion_no_socios_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socios',
            name='regalo',
            field=models.BooleanField(default=False),
        ),
    ]
