# Generated by Django 5.0.2 on 2024-06-26 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Socios', '0013_socios_regalo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripciones',
            name='destino',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='inscripciones',
            name='distancia',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inscripciones',
            name='fecha',
            field=models.CharField(max_length=16),
        ),
    ]
