# Generated by Django 5.0.2 on 2024-07-04 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Socios', '0014_alter_inscripciones_destino_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socios',
            old_name='apellido',
            new_name='apellidos',
        ),
    ]
