# Generated by Django 5.0.2 on 2024-07-27 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Socios', '0017_alter_inscripciones_recaudacion_no_socios_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion_socio',
            name='pago',
            field=models.BooleanField(default=False),
        ),
    ]
