# Generated by Django 5.0.2 on 2024-08-10 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Socios', '0020_inscripciones_total_no_socios_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripciones',
            name='total_guias',
            field=models.IntegerField(default=0),
        ),
    ]
