# Generated by Django 5.0.2 on 2024-08-10 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Socios', '0021_inscripciones_total_guias'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion_socio',
            name='guia',
            field=models.BooleanField(default=False),
        ),
    ]
