# Generated by Django 5.0.2 on 2025-01-17 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Socios', '0022_inscripcion_socio_guia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inscripciones',
            old_name='recaudacion_no_socios',
            new_name='recaudacion_banco',
        ),
        migrations.RenameField(
            model_name='inscripciones',
            old_name='recaudacion_socios',
            new_name='recaudacion_total',
        ),
    ]
