# Generated by Django 5.0.2 on 2025-01-31 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Socios', '0023_rename_recaudacion_no_socios_inscripciones_recaudacion_banco_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inscripciones',
            old_name='recaudacion_total',
            new_name='recaudacion_metálico',
        ),
    ]
