# Generated by Django 5.0.2 on 2025-12-12 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Socios', '0024_rename_recaudacion_total_inscripciones_recaudacion_metálico'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inscripciones',
            old_name='recaudacion_metálico',
            new_name='recaudacion_metalico',
        ),
        migrations.AlterField(
            model_name='inscripciones',
            name='dificultad',
            field=models.CharField(choices=[('BAJA', 'BAJA'), ('MEDIA-BAJA', 'MEDIA-BAJA'), ('MEDIA', 'MEDIA'), ('MEDIA-ALTA', 'MEDIA-ALTA'), ('ALTA', 'ALTA')], default='BAJA', max_length=20),
        ),
    ]
